# Generated by Django 4.0.6 on 2022-08-23 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedule', '0005_rename_group_schedule_sport_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='date', to='schedule.schedule')),
            ],
            options={
                'db_table': 'visit_log',
            },
        ),
    ]
