# Generated by Django 4.0.6 on 2022-08-17 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('link', models.URLField(max_length=256)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'videos',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
