# Generated by Django 4.0.6 on 2022-08-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_rename_name_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
