# Generated by Django 4.0.6 on 2022-08-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_remove_video_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
