# Generated by Django 4.0.6 on 2022-08-27 03:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='readers',
            field=models.ManyToManyField(blank=True, related_name='readed_messages', to=settings.AUTH_USER_MODEL),
        ),
    ]
