# Generated by Django 4.0.6 on 2022-08-02 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(upload_to='')),
                ('open', models.BooleanField(default=True)),
                ('number', models.IntegerField()),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
    ]
