# Generated by Django 4.0.6 on 2022-08-08 17:14

from django.conf import settings
from django.db import migrations, models
import event.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('address', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('cover', models.ImageField(null=True, upload_to=event.utils.PathAndHash('events/covers'))),
                ('open', models.BooleanField(default=True)),
                ('hidden', models.BooleanField(default=False)),
                ('number', models.IntegerField(default=0)),
                ('members', models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['start_date'],
            },
        ),
    ]
