# Generated by Django 4.0.6 on 2022-08-05 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0003_event_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='students',
            field=models.ManyToManyField(related_name='events', to=settings.AUTH_USER_MODEL),
        ),
    ]
