# Generated by Django 4.0.6 on 2022-08-22 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_alter_gym_cover'),
        ('sport_groups', '0002_sportgroup_trainer_alter_sportgroup_members'),
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='sport_groups.sportgroup'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='gym',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedules', to='gyms.gym'),
        ),
    ]
