# Generated by Django 4.0.6 on 2022-08-23 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_alter_schedule_group_alter_schedule_gym'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='schedule',
            name='finish_time_gte_start_time',
        ),
        migrations.AlterModelTable(
            name='schedule',
            table='schedules',
        ),
    ]
