# Generated by Django 4.0.6 on 2022-08-23 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_remove_schedule_finish_time_gte_start_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='group',
            new_name='sport_group',
        ),
    ]
