# Generated by Django 4.0.6 on 2022-08-03 23:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('min_age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('max_age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(150), django.core.validators.MinValueValidator(1)])),
                ('members', models.ManyToManyField(related_name='sport_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sport_groups',
            },
        ),
        migrations.AddConstraint(
            model_name='sportgroup',
            constraint=models.CheckConstraint(check=models.Q(('max_age__gte', django.db.models.expressions.F('min_age'))), name='max_age_gte_min_age'),
        ),
    ]
