# Generated by Django 4.0.6 on 2022-08-27 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_alter_message_readers'),
        ('sport_groups', '0004_alter_sportgroup_members_alter_sportgroup_trainer'),
    ]

    operations = [
        migrations.AddField(
            model_name='sportgroup',
            name='chat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chats.chat'),
        ),
    ]
