# Generated by Django 4.0.6 on 2022-08-20 22:01

import club_content.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('cover', models.ImageField(null=True, upload_to=club_content.utils.PathAndHash('content/covers'))),
                ('number', models.IntegerField(default=0)),
                ('hidden', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'club_content',
            },
        ),
    ]
