# Generated by Django 4.0.6 on 2022-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instruction',
            name='link',
            field=models.URLField(),
        ),
    ]
