# Generated by Django 4.0.6 on 2022-08-21 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gyms', '0002_gym_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='trainers',
            field=models.ManyToManyField(blank=True, related_name='gyms', to=settings.AUTH_USER_MODEL),
        ),
    ]
