# Generated by Django 4.0.6 on 2022-08-21 10:29

from django.db import migrations, models
import gyms.models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_gym_trainers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='cover',
            field=models.ImageField(null=True, upload_to=gyms.models.GymsPathAndHash('covers')),
        ),
    ]
