# Generated by Django 4.0.6 on 2022-08-03 14:08

import authentication.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[('ST', 'Student'), ('PR', 'Parent'), ('TR', 'Trainer'), ('MD', 'Moderator'), ('AD', 'Administrator')], max_length=2, null=True)),
                ('full_name', models.CharField(max_length=100, null=True)),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: ...', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}')])),
                ('password', models.CharField(max_length=100, null=True)),
                ('active', models.BooleanField(default=True)),
                ('admin', models.BooleanField(default=False)),
                ('superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('parents', models.ManyToManyField(related_name='children', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: ...', regex='^(\\+7|7|8)?[\\s\\-]?\\(?[489][0-9]{2}\\)?[\\s\\-]?[0-9]{3}[\\s\\-]?[0-9]{2}[\\s\\-]?[0-9]{2}')])),
                ('otp', models.CharField(blank=True, max_length=9, null=True)),
                ('count', models.IntegerField(default=0)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b24_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('sport_school', models.CharField(max_length=200)),
                ('tech_qualification', models.CharField(max_length=100)),
                ('sport_qualification', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('med_certificate_date', models.DateTimeField()),
                ('insurance_policy_date', models.DateTimeField()),
                ('passport_or_birth_certificate', models.ImageField(upload_to=authentication.models.UserPathAndHash('passport_or_birth_certificate'))),
                ('oms_policy', models.ImageField(upload_to=authentication.models.UserPathAndHash('oms_policy'))),
                ('school_ref', models.ImageField(upload_to=authentication.models.UserPathAndHash('school_ref'))),
                ('insurance_policy', models.ImageField(upload_to=authentication.models.UserPathAndHash('insurance_policy'))),
                ('tech_qual_diplo', models.ImageField(upload_to=authentication.models.UserPathAndHash('tech_qual_diplo'))),
                ('med_certificate', models.ImageField(upload_to=authentication.models.UserPathAndHash('med_certificate'))),
                ('foreign_passport', models.ImageField(upload_to=authentication.models.UserPathAndHash('foreign_passport'))),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_birth_date', models.DateTimeField()),
                ('father_phone_number', models.CharField(max_length=100)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_birth_date', models.DateTimeField()),
                ('mother_phone_number', models.CharField(max_length=100)),
                ('mother_email', models.EmailField(max_length=254)),
                ('training_place', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('diploma', models.ImageField(upload_to=authentication.models.UserPathAndHash('diploma'))),
                ('inn', models.ImageField(upload_to=authentication.models.UserPathAndHash('inn'))),
                ('snils', models.ImageField(upload_to=authentication.models.UserPathAndHash('snils'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to=authentication.models.DocumentPathAndHash('image'))),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='authentication.userprofile')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
