# Generated by Django 4.0.6 on 2022-08-05 22:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='parents',
            field=models.ManyToManyField(blank=True, related_name='children', to=settings.AUTH_USER_MODEL),
        ),
    ]
