# Generated by Django 4.0.6 on 2022-08-01 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_phoneotp_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='used',
            field=models.BooleanField(default=False),
        ),
    ]
