# Generated by Django 4.0.6 on 2022-08-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_photo_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='superuser',
        ),
    ]
