# Generated by Django 4.0.6 on 2022-08-21 17:02

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_remove_user_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='image',
            field=models.FileField(upload_to=authentication.models.DocumentsPathAndHash('other')),
        ),
        migrations.AlterField(
            model_name='user',
            name='diploma',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('diploma')),
        ),
        migrations.AlterField(
            model_name='user',
            name='foreign_passport',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('foreign_passport')),
        ),
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('inn')),
        ),
        migrations.AlterField(
            model_name='user',
            name='insurance_policy',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('insurance_policy')),
        ),
        migrations.AlterField(
            model_name='user',
            name='med_certificate',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('med_certificate')),
        ),
        migrations.AlterField(
            model_name='user',
            name='oms_policy',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('oms_policy')),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_or_birth_certificate',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('passport_or_birth_certificate')),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_ref',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('school_ref')),
        ),
        migrations.AlterField(
            model_name='user',
            name='snils',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('snils')),
        ),
        migrations.AlterField(
            model_name='user',
            name='tech_qual_diplo',
            field=models.FileField(null=True, upload_to=authentication.models.DocumentsPathAndHash('tech_qual_diplo')),
        ),
    ]
