# Generated by Django 4.0.6 on 2022-08-24 16:31

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_alter_user_trainer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=authentication.models.UserPathAndHash('photo')),
        ),
    ]
