# Generated by Django 4.0.6 on 2022-08-08 17:14

from django.db import migrations, models
import django.db.models.deletion
import news.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_times', models.IntegerField(default=0)),
                ('order', models.IntegerField()),
                ('hidden', models.BooleanField(default=False)),
                ('cover', models.ImageField(upload_to=news.models.NewsPathAndHash('covers'))),
            ],
            options={
                'db_table': 'news',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=news.models.NewsPathAndHash('images'))),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news')),
            ],
            options={
                'db_table': 'news_images',
            },
        ),
    ]
