# Generated by Django 4.0.6 on 2022-08-01 22:13

from django.db import migrations, models
import news.utils


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(upload_to=news.utils.PathAndHash('news/covers')),
        ),
        migrations.AlterField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to=news.utils.PathAndHash('news/images')),
        ),
    ]
