# Generated by Django 4.0.6 on 2022-08-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_news_cover_alter_news_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['order', '-created_at']},
        ),
    ]
