# Generated by Django 4.0.6 on 2022-08-11 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
