# Generated by Django 4.0.6 on 2022-08-03 13:45

from django.db import migrations, models
import news.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_news_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='cover',
            field=models.ImageField(upload_to=news.models.NewsPathAndHash('covers')),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(upload_to=news.models.NewsPathAndHash('images')),
        ),
    ]
