# Generated by Django 4.0.6 on 2022-08-19 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbill',
            old_name='active',
            new_name='is_active',
        ),
    ]
