# Generated by Django 4.0.6 on 2022-08-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_rename_active_userbill_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbill',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='pay_account_bill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='user_bill_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
