# Generated by Django 4.0.6 on 2022-08-19 22:21

from django.db import migrations, models
import invoice.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_userbill_paid_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbill',
            old_name='_paid',
            new_name='paid',
        ),
        migrations.AlterField(
            model_name='bill',
            name='period',
            field=models.DurationField(blank=True, null=True, validators=[invoice.models.validate_min]),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='yookassa_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
