# Generated by Django 4.0.6 on 2022-08-22 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice', '0004_rename__paid_userbill_paid_alter_bill_period_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='pay_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.payaccount'),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_users', to='invoice.bill'),
        ),
        migrations.AlterField(
            model_name='userbill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to=settings.AUTH_USER_MODEL),
        ),
    ]
