# Generated by Django 4.0.6 on 2022-08-03 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b24_id', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('birth_date', models.DateTimeField()),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=200)),
                ('sport_school', models.CharField(max_length=200)),
                ('tech_qualification', models.CharField(max_length=100)),
                ('sport_qualification', models.CharField(max_length=100)),
                ('weight', models.IntegerField()),
                ('height', models.IntegerField()),
                ('med_certificate_date', models.DateTimeField()),
                ('insurance_policy_date', models.DateTimeField()),
                ('passport_or_birth_certificate', models.ImageField(upload_to=profiles.models.UserPathAndHash('passport_or_birth_certificate'))),
                ('oms_policy', models.ImageField(upload_to=profiles.models.UserPathAndHash('oms_policy'))),
                ('school_ref', models.ImageField(upload_to=profiles.models.UserPathAndHash('school_ref'))),
                ('insurance_policy', models.ImageField(upload_to=profiles.models.UserPathAndHash('insurance_policy'))),
                ('tech_qual_diplo', models.ImageField(upload_to=profiles.models.UserPathAndHash('tech_qual_diplo'))),
                ('med_certificate', models.ImageField(upload_to=profiles.models.UserPathAndHash('med_certificate'))),
                ('foreign_passport', models.ImageField(upload_to=profiles.models.UserPathAndHash('foreign_passport'))),
                ('father_full_name', models.CharField(max_length=100)),
                ('father_birth_date', models.DateTimeField()),
                ('father_phone_number', models.CharField(max_length=100)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_full_name', models.CharField(max_length=100)),
                ('mother_birth_date', models.DateTimeField()),
                ('mother_phone_number', models.CharField(max_length=100)),
                ('mother_email', models.EmailField(max_length=254)),
                ('training_place', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=200)),
                ('diploma', models.ImageField(upload_to=profiles.models.UserPathAndHash('diploma'))),
                ('inn', models.ImageField(upload_to=profiles.models.UserPathAndHash('inn'))),
                ('snils', models.ImageField(upload_to=profiles.models.UserPathAndHash('snils'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profiles',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(upload_to=profiles.models.DocumentPathAndHash('image'))),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'documents',
            },
        ),
    ]
